name: generate and publish manifest

on:
  push:
    branches: [ main ]

env:
  artifact: vfox-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set repo name
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "VERSION=$(echo ${{ github.ref }} | cut -d'/' -f3 | cut -c2-)" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: '5.3.5'

      - name: Install dependencies
        run: |
          sudo apt-get install luarocks
          sudo luarocks install dkjson

      - name: Run script
        run: |
          sudo lua -e '
          require("metadata"); 
          local dkjson = require("dkjson"); 
          PLUGIN.download_url = "https://github.com/${{ github.repository }}/releases/download/${{ github.ref }}/${REPO_NAME}_v${VERSION}.zip"; 
          local str = dkjson.encode(PLUGIN); 
          print(str)' > manifest.json
      - name: Compress build files
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          directory: "artifacts"
          filename: "${REPO_NAME}_${{ github.ref }}.zip"
#          exclusions: "*.json *.pdb"
      - name: Publish release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ env.artifact }}/${REPO_NAME}_${VERSION}.zip
          tag: v${VERSION}
          file_glob: true
      - name: Publish manifest
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./manifest*.json
          tag: "manifest"
          overwrite: true
          file_glob: true